apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
spec:
  selector:
     app: eureka-server
  type: LoadBalancer
  # type: ClusterIP
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
---    
#apigateway
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: default
spec:
  selector:
     app: apigateway
  # type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
---    
#ProductService
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: default
spec:
  selector:
     app: product
  type: ClusterIP
  # type: LoadBalancer
  ports:
  - port: 64421
    protocol: TCP
    targetPort: 64421
---    
#ProductService
# apiVersion: v1
# kind: Service
# metadata:
#   name: search
#   namespace: default
# spec:
#   selector:
#      app: search
#   # type: ClusterIP
#   type: LoadBalancer
#   ports:
#   - port: 44421
#     protocol: TCP
#     targetPort: 44421
---    
#ProductService
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: default
spec:
  selector:
     app: order
  type: ClusterIP
  # type: LoadBalancer
  ports:
  - port: 54421
    protocol: TCP
    targetPort: 54421
